### ISSUE TITLE
UI Deployment tags

### ISSUE THREAD

**Issue by andromeda306** [aws-samples/datamesh-ui#19]
Is there a way to provide tags during the deploy-ui phase? My organization SCP requires all resources be tagged otherwise I cannot deploy. I've made the following attempts but none have been successful.
 
1) created amplify/backend and added a tags.json file
2) added tags.json into backend/ 
3) added tags.json into src/Backend
4) the same as above in the datamesh-ui dir that is downloaded as part of install.sh

**Comment by jmgtan** [comment]
Have you tried this? https://aws.amazon.com/blogs/mobile/organizing-your-aws-resources-using-tags-with-the-amplify-cli/ and https://docs.amplify.aws/cli/project/tags/#setting-up-tags-in-a-new-project. Default tags are provided, you can override those after running the amply init. You should see the breakdown of the commands in the `src/package.json`, specifically the `deploy-ui`. You don't have to use the `deploy-ui` command, but instead break it down and insert it into the `install.sh` file and add tags to comply with your company's SCP.

Take note amplify is only used to integrate Cognito. We don't use it for hosting or anything else. UI hosting is done via S3 and CloudFront.
