### ISSUE TITLE
AccessDenied on front-end

### ISSUE THREAD

**Issue by whrocha** [aws-samples/datamesh-ui#9]
I've getting the following error when I try to use the Data Mesh UI.

```xml
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>D0YPP76NR8FTMJ5S</RequestId>
    <HostId>SfM39QLm4tyeTDjauvq0exLUbb+/LpwIW8Zc1EiZXjPQEgMtxLYis7CCNbeeVJzMgMmpBpXAaBI=</HostId>
</Error>
```

**Comment by jmgtan** [comment]
Are you deploying via Amplify or S3? We’ve only tested deploying via Amplify hosting for the time being.

**Comment by jmgtan** [comment]
Will close this, the install script now deploys to S3 + CloudFront
